General:
  Measurement: "pairing_limits"
  POI: "Signal_norm"
  HistogramFolder: "histograms/"
  InputPath: "inputs/histograms.root:{RegionPath}/{SamplePath}/{VariationPath}"
  VariationPath: "hh_mass_reco_signal_4b_GN2v01_77"

Regions:
  - Name: "Signal_region"
    RegionPath: "SR"

Samples:
  - Name: "Data"
    SamplePath: "Background"
    Data: True

  - Name: "ggF_k01"
    SamplePath: "Signal"
    DisableStaterror: False

  - Name: "Background"
    SamplePath: "Background"
    DisableStaterror: False

NormFactors:
  - Name: "Signal_norm"
    Samples: "ggF_k01"
    Nominal: 1
    Bounds: [0, 20]
