General:
  Measurement: "pairing_limits"
  POI: "Signal_norm"
  HistogramFolder: "histograms/"
  InputPath: "inputs/histograms.root:{RegionPath}/{SamplePath}/{VariationPath}"
  VariationPath: "hh_mass_reco_signal_4b_GN2v01_77"

Regions:
  - Name: "min_deltar_pairing"
    RegionPath: "SR_min_deltar_pairing"
  - Name: "max_deltar_pairing"
    RegionPath: "SR_max_deltar_pairing"
  - Name: "min_mass_true_pairing"
    RegionPath: "SR_min_mass_true_pairing"
  - Name: "min_mass_diff_pairing"
    RegionPath: "SR_min_mass_diff_pairing"
  - Name: "min_mass_center_pairing"
    RegionPath: "SR_min_mass_center_pairing"

Samples:
  - Name: "Data"
    SamplePath: "Background"
    Data: True

  - Name: "ggF_k01"
    SamplePath: "Signal"
    DisableStaterror: False

  - Name: "Background"
    SamplePath: "Background"
    DisableStaterror: False

NormFactors:
  - Name: "Signal_norm"
    Samples: "ggF_k01"
    Nominal: 1
    Bounds: [0, 20]

# Systematics:
#   - Name: Luminosity
#     Up:
#       Normalization: 0.008
#     Down:
#       Normalization: -0.008
#     Type: Normalization

#   - Name: "Modeling"
#     Up:
#       VariationPath: "Modeling_Up"
#     Down:
#       Symmetrize: True
#     Samples: "Background"
#     Type: "NormPlusShape"

#   - Name: "WeightBasedModeling"
#     Up:
#       VariationPath: "WeightBasedModeling_Up"
#     Down:
#       VariationPath: "WeightBasedModeling_Down"
#     Samples: "Background"
#     Type: "NormPlusShape"
